# General set up
language: cpp
cache: apt

matrix:
  include:
    - os: linux
      dist: precise
      sudo: required
      compiler: gcc
      env: TRAVIS_DIST=precise QT_VERSION=5.4.2
    - os: linux
      dist: precise
      sudo: required
      compiler: gcc
      env: TRAVIS_DIST=precise QT_VERSION=5.6.2
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: TRAVIS_DIST=trusty QT_VERSION=5.4.2
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: TRAVIS_DIST=trusty QT_VERSION=5.6.2

# Install dependencies
install:
 - source travis/prepare.sh # installs qt and cmake. need to source because some env vars are set from there

# Actual work
before_script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH ..
script:
 - make -j4 && make test ARGS="-V"
