blank_issues_enabled: true
# contact_links:
#   - name: PrismLauncher Matrix Support Room
#     url: about:blank # Add proper link in the future
#     about: (⚠ Room not created yet ⚠) Please ask for support here before opening an issue.
