name: Build Application

on:
  push:
    branches-ignore:
      - 'stable'
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - '**.nix'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - '**.nix'
  workflow_dispatch:

jobs:

  build_debug:
    name: Build Debug
    uses: ./.github/workflows/build.yml
    with:
      build_type: Debug

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release
